### ISSUE TITLE
Infer Derived Executor Properties without explcitly passing them in Base Executor

### ISSUE THREAD

**Issue by shrijitsingh99** [shrijitsingh99/unified-executors#13]
Can't `Interface`, `Cardinality`, etc... be all inferred from `Derived`? i.e. inside the class you have something like
```cpp
using Derived::Interface;
using Derived::Cardinality;
```

Edit: I know we discussed this last time and your argument was
> Then every derived class needs to define these

I'm not convinced you need to pass the derived class back to base in this design, just for an equivalence operator.

_Originally posted by @SergioRAgostinho in https://github.com/shrijitsingh99/unified-executors/pull/7_

**Comment by SergioRAgostinho** [comment]
I think you can focus on only on the second part of my comment. (no need for derived in the template parameter). For the first part
> Then every derived class needs to define these

I acknowledge this is true and cumbersome.

**Comment by shrijitsingh99** [comment]
Solved, with the removal of base executor class.
