### ISSUE TITLE
Tag disaptching based overloading for executors

### ISSUE THREAD

**Issue by shrijitsingh99** [shrijitsingh99/unified-executors#16]
The current designs simple tag dispatching or templated property based overloading as mentioned by  @SergioRAgostinho over here: https://github.com/shrijitsingh99/unified-executors/pull/7#discussion_r448834939

```cpp
template<typename allocator_t>
void mmul(inline_executor<oneway_t, single_t, blocking_t::always_t, allocator_t> &ex, MatrixXd &a, MatrixXd &b, MatrixXd &c){...}
```

The reasoning behind this is to make the overloading technique completely agnostic of the executor design. So that even if there is a change in the executor design we there will be no need to modify the overloads.

For example, in the proposed approach above, the assumption is made that there will be these fixed 4 properties, and if there is an additional property added in the future the overload breaks.

One more place the above design breaks is if users create a new executor inserting from `inline_executor` the overload will not work for the above design. Nor would this design be able to accommodate combined executor.

In the current design, 
```cpp
template <typename Executor,
          typename executor::instance_of_base<inline_executor, Executor> = 0>
void mmul(const Executor ex, const MatrixXd& a, const MatrixXd& b, MatrixXd& c)
{...}
```
the tag dispatching part is hidden in `instance_of_base<inline_executor, Executor>`, so by simply changing the behavior of `instance_of _base` we can support derived or combined executors.
There is also no dependence on the properties or the executor design, making it very flexible and extensible for any features we want to add in the future.

**Comment by SergioRAgostinho** [comment]
> One more place the above design breaks is if users create a new executor inserting from `inline_executor` the overload will not work for the above design. Nor would this design be able to accommodate combined executor.

Include code snippet please.
