### ISSUE TITLE
Use cases for `execute` and `bulk_execute` 

### ISSUE THREAD

**Issue by shrijitsingh99** [shrijitsingh99/unified-executors#19]
While integrating PCL with executors, the majority of the use cases involved using executors for tag dispatching purposes only, and the use of `execute` and `bulk_execute` could not be seen anywhere since specialized code was needed for each case (OMP, SSE,etc..) and it wasn't possible to use something like:

```cpp

auto generic_func = [](){...};
exec.execute(generic_func);

```
As no such generic function exists which could be run on any type of executor, without the need for specialized code.

**Comment by kunaltyagi** [comment]
Some filters would be bulk_executable, but only after refactoring the code regarding the range they should run in
```cpp
// original
void filter() {
  for (index_t i = 0; i < indices.size(); ++i) {
    // do something
  }
}
// refactored
void filter(index_t from, index_t to) {
  for (index_t i = from; i < to; ++i) {
    // do something
  }
}
```
The second example can be launched using `bulk_execute` and `execute`. I don't remember how the proposal changed wrt this (proposal referred to SIMD usage: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0443r12.html)

**Comment by shrijitsingh99** [comment]
> The second example can be launched using bulk_execute

I can't seem to see how. Since `bulk_execute` for inline is just a simple for loop and for OMP the filter function itself would need to be modified.

`bulk_execute` works great if the function is mutually exclusive between iterations and its implementation doesn't change with execution contexts. Filter implementation would need to be changed for OMP.

**Comment by kunaltyagi** [comment]
Please check:
* features/normal_3d_omp (and other features too)
* filters/fast_bilateral_omp

Refactoring the update portion of filters:
```cpp
// current
if (remove) {
  removed_indices[rii++] = idx;
} else {
  indices[oii++] = idx
}
resize_both_vectors(rii, oii);

// updated
#pragma parallelize this magically
if (remove) {
  removed_indices[thread_offset + rii[thread_id]++] = idx;
} else {
  indices[thread_offset + oii[thread_id]++] = idx
}
// this part needs to be log_2(n) merge logic
resize_both_vectors(num_threads, rii, oii);
```

After this update, there should not be a significant difference in filter implementation for most filters
